# Generated by Django 4.1.5 on 2023-02-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_remove_auction_bids_bid_auction'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='num_items',
            field=models.IntegerField(default=1),
        ),
    ]
