# Generated by Django 4.1.5 on 2023-02-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_auction_num_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('ACT', 'Active'), ('CMP', 'Complete'), ('INACT', 'Inactive')], default='ACT', max_length=10),
        ),
        migrations.AddField(
            model_name='bid',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
